{{- if and (include "opensearch.cluster_manager.enabled" .) .Values.cluster_manager.autoscaling.enabled }}
apiVersion: {{ include "common.capabilities.hpa.apiVersion" ( dict "context" $ ) }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "opensearch.cluster_manager.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: cluster_manager
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: {{ template "common.capabilities.statefulset.apiVersion" . }}
    kind: StatefulSet
    name: {{ include "opensearch.cluster_manager.fullname" . }}
  minReplicas: {{ .Values.cluster_manager.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.cluster_manager.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.cluster_manager.autoscaling.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.cluster_manager.autoscaling.targetCPU }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.cluster_manager.autoscaling.targetCPU }}
        {{- end }}
    {{- end }}
    {{- if .Values.cluster_manager.autoscaling.targetMemory }}
    - type: Resource
      resource:
        name: memory
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.cluster_manager.autoscaling.targetMemory }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.cluster_manager.autoscaling.targetMemory }}
        {{- end }}
    {{- end }}
{{- end }}