{{- if (include "opensearch.createSecret" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-s3
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  access_key: {{ .Values.s3Snapshots.config.s3.client.default.access_key | b64enc | quote }}
  secret_key: {{ .Values.s3Snapshots.config.s3.client.default.secret_key | b64enc | quote }}

---
{{- end }}
